var AXNlang = {
    "FR": {
        "YOUR_SEARCH": "Votre recherche",
        "REF": "Référence",
        "PRICE": "Prix",
        "SURFACE": "Surface",
        "TYPO": "Typologies",
        "FLOOR": "Etage",
        "ALL": "Tous",
        "NONE": "Aucun",
        "FAVORITE": "Favori",
        "DOWNLOAD": "Télécharger",
        "DISPLAY": "Visualiser",
        "NO_RESULT": "Aucun résultat",
        "NO_FAVORITE": "Aucun lot en favori",
        "CONTACT": "Contact",
        "LAST_NAME": "Nom",
        "FIRST_NAME": "Prénom",
        "EMAIL": "Mail",
        "PHONE": "Téléphone",
        "NOT_SPECIFIED": "Non renseigné",
        "SUMMARY": "Récapitulatif",
        "CREATE_FILE": "Création du fichier"
    },
    "EN": {
        "YOUR_SEARCH": "Your search",
        "REF": "Reference",
        "PRICE": "Price",
        "SURFACE": "Surface",
        "TYPO": "Type",
        "FLOOR": "Floor",
        "ALL": "All",
        "NONE": "None",
        "FAVORITE": "Favorite",
        "DOWNLOAD": "Download",
        "DISPLAY": "Display",
        "NO_RESULT": "No result",
        "NO_FAVORITE": "No favorite",
        "CONTACT": "Contact",
        "LAST_NAME": "Last name",
        "FIRST_NAME": "First name",
        "EMAIL": "Mail",
        "PHONE": "Phone",
        "NOT_SPECIFIED": "Not specified",
        "SUMMARY": "Summary",
        "CREATE_FILE": "Creating file"
    }
}